---
# Branchements
# ------------
#
# GPIO27 : prise 1 - rouge et orange
# GPIO26 : prise 1 - vert et bleu
# GPIO25 : prise 2 - rouge et orange
# GPIO33 : prise 2 - vert et bleu
#
# GPIO32 : led sur interrupteur
# GPIO14 : interrupteur

substitutions:
  devicename: guirlande-a-bouboules
  upper_devicename: Guirlande a bouboules

packages:
  device_base: !include common/device_base.yaml
  device_esp32: !include common/device_esp32.yaml

esphome:
  name_add_mac_suffix: false
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: button_led
          brightness: 100%
      - light.turn_on:
          id: guirlande1
          effect: &effet_par_defaut_ch1 "Bip bip 2"
      - light.turn_on:
          id: guirlande2
          effect: &effet_par_defaut_ch2 "Bip bip 2"

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

logger:
  level: INFO
  #level: DEBUG
  #level: VERBOSE
  #level: VERY_VERBOSE
  #logs:
  #  scheduler: INFO

wifi:
  manual_ip:
    # pour une connection rapide, et pour que le conteneur docker esphome puisse trouver l'ESP sans mDNS
    static_ip: 192.168.1.186
    gateway: 192.168.1.1
    subnet: 255.255.255.0

## Device-specific

preferences:
  flash_write_interval: 10min

globals:
  - id: desync_enabled
    type: bool
    restore_value: no
    initial_value: 'true'

script:
  # Script de désynchronisation pour guirlande1
  - id: desync_guirlande1
    mode: restart
    then:
      - lambda: |-
          if (id(guirlande1).get_effect_name() == "Bip bip 2" && id(desync_enabled)) {
            // Probabilité de 20% de déclencher une désync
            if (random_float() < 0.2) {
              ESP_LOGD("desync", "Désynchronisation guirlande1");
              // Pause brève de l'effet
              auto call = id(guirlande1).turn_on();
              call.set_effect("None");
              call.perform();
            }
          }
      - delay: !lambda "return random_float() * 300 + 100;"  # 100-400ms de pause
      - lambda: |-
          if (id(guirlande1).get_effect_name() == "None" && id(guirlande1).current_values.is_on()) {
            auto call = id(guirlande1).turn_on();
            call.set_effect("Bip bip 2");
            call.perform();
          }

  # Script de désynchronisation pour guirlande2
  - id: desync_guirlande2
    mode: restart
    then:
      - lambda: |-
          if (id(guirlande2).get_effect_name() == "Bip bip 2" && id(desync_enabled)) {
            // Probabilité de 20% de déclencher une désync
            if (random_float() < 0.2) {
              ESP_LOGD("desync", "Désynchronisation guirlande2");
              // Pause brève de l'effet
              auto call = id(guirlande2).turn_on();
              call.set_effect("None");
              call.perform();
            }
          }
      - delay: !lambda "return random_float() * 300 + 100;"  # 100-400ms de pause
      - lambda: |-
          if (id(guirlande2).get_effect_name() == "None" && id(guirlande2).current_values.is_on()) {
            auto call = id(guirlande2).turn_on();
            call.set_effect("Bip bip 2");
            call.perform();
          }

interval:
  # Intervalle de désynchronisation pour "Bip bip 2"
  # Intervalles différents pour chaque guirlande = désynchronisation naturelle
  - interval: 2.3s  # Intervalle premier (non divisible par l'autre)
    then:
      - script.execute: desync_guirlande1

  - interval: 3.1s  # Intervalle différent pour la 2ème guirlande
    then:
      - script.execute: desync_guirlande2

  - interval: 1s
    then:
      - if:
          condition:
            or:
              - light.is_on: guirlande1
              - light.is_on: guirlande2
          then:
            - if:
                condition:
                  light.is_off: button_led
                then:
                  - logger.log: "button is OFF, turning ON"
                  - light.turn_on:
                      id: button_led
                      transition_length: 0.1s
                      brightness: 100%
          else:
            - if:
                condition:
                  light.is_on: button_led
                then:
                  - logger.log: "button is ON, turning OFF"
                  - light.turn_off:
                      id: button_led
                      # doit etre inférieur a l'intervalle de cette séquence, sinon light.is_on toujours vrai
                      transition_length: 0.1s

# inspiration : https://github.com/esphome/feature-requests/issues/2501
output:
  - platform: ledc
    id: channel1_pin1
    pin:
      number: 27
    channel: 0
    max_power: 50%
    phase_angle: 180
  - platform: ledc
    id: channel1_pin2
    pin: 26
    channel: 1
    max_power: 50%
  - platform: ledc
    id: channel2_pin1
    pin:
      number: 25
    channel: 4
    max_power: 50%
    phase_angle: 180
  - platform: ledc
    id: channel2_pin2
    pin: 33
    channel: 5
    max_power: 50%
  - platform: ledc
    id: push_button_led
    pin: 32
    channel: 2


light:
  - platform: status_led
    internal: true
    id: status_led_shared
    output: push_button_led
  - platform: monochromatic
    name: "LED sur interrupteur"
    id: button_led
    output: push_button_led
  - platform: cwww
    name: "Guirlande 1"
    id: guirlande1
    cold_white: channel1_pin1
    warm_white: channel1_pin2
    cold_white_color_temperature: &cold 0 Mireds
    warm_white_color_temperature: &warm 500 Mireds
    effects: &effects
      - strobe:
          name: "Bip bip 1"
          colors:
            # Phase 1 : alternance lente (5 répétitions = 10 étapes)
            - {duration: 1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            # Phase 2 : alternance moyenne (20 répétitions = 40 étapes)
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            # Phase 3 : alternance très rapide avec 4 états (50 répétitions = 200 étapes, mais limité pour la lisibilité)
            # Note: le strobe boucle automatiquement, donc on peut réduire le nombre pour que ça soit gérable
            - {duration: 0.1s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.1s, warm_white: 100%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.1s, warm_white: 100%, cold_white: 100%}
      - strobe:
          name: "Bip bip 2"
          colors:
            # Progression fluide : lent → rapide → lent
            # Phase accélération (duration: 1s → 0.1s)
            - {duration: 1.0s, transition_length: 0.5s, warm_white: 100%, cold_white: 20%}
            - {duration: 1.0s, transition_length: 0.5s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.9s, transition_length: 0.45s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.9s, transition_length: 0.45s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.8s, transition_length: 0.4s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.8s, transition_length: 0.4s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.7s, transition_length: 0.35s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.7s, transition_length: 0.35s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.6s, transition_length: 0.3s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.6s, transition_length: 0.3s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.5s, transition_length: 0.25s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.5s, transition_length: 0.25s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.4s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.4s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.15s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.15s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.2s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.2s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.15s, transition_length: 0.08s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.15s, transition_length: 0.08s, warm_white: 20%, cold_white: 100%}
            # Phase rapide (maintien quelques cycles)
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.1s, transition_length: 0.05s, warm_white: 20%, cold_white: 100%}
            # Phase décélération (duration: 0.1s → 1s)
            - {duration: 0.15s, transition_length: 0.08s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.15s, transition_length: 0.08s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.2s, transition_length: 0.1s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.2s, transition_length: 0.1s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.3s, transition_length: 0.15s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.3s, transition_length: 0.15s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.4s, transition_length: 0.2s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.4s, transition_length: 0.2s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.5s, transition_length: 0.25s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.5s, transition_length: 0.25s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.6s, transition_length: 0.3s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.6s, transition_length: 0.3s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.7s, transition_length: 0.35s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.7s, transition_length: 0.35s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.8s, transition_length: 0.4s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.8s, transition_length: 0.4s, warm_white: 20%, cold_white: 100%}
            - {duration: 0.9s, transition_length: 0.45s, warm_white: 100%, cold_white: 20%}
            - {duration: 0.9s, transition_length: 0.45s, warm_white: 20%, cold_white: 100%}
            - {duration: 1.0s, transition_length: 0.5s, warm_white: 100%, cold_white: 20%}
            - {duration: 1.0s, transition_length: 0.5s, warm_white: 20%, cold_white: 100%}
      - strobe:
          name: "Arc-en-ciel"
          colors:
            - duration: 10s
              transition_length: 2s
              cold_white: 100%
              warm_white: 100%
            - duration: 1s
              transition_length: 0.2s
              cold_white: 100%
              warm_white: 20%
            - duration: 10s
              transition_length: 2s
              cold_white: 100%
              warm_white: 100%
            - duration: 1s
              transition_length: 0.2s
              cold_white: 20%
              warm_white: 100%
      - flicker:
          name: "Scintillement profond"
          alpha: 50%
          intensity: 50%
      - flicker:
          name: "Scintillement léger"
          alpha: 80%
          intensity: 10%
      - random:
          name: "Aléatoire lent"
          transition_length: 1s
          update_interval: 2s
      - random:
          name: "Aléatoire moyen"
          transition_length: 0.4s
          update_interval: 0.4s
      - random:
          name: "Aléatoire rapide"
          transition_length: 0.1s
          update_interval: 0.1s
      - random:
          name: "Aléatoire énervé"
          transition_length: 0.02s
          update_interval: 0.02s
      - strobe:
          name: "Alternance lente"
          colors:
            - duration: 7s
              transition_length: 5s
              warm_white: 100%
              cold_white: 20%
            - duration: 7s
              transition_length: 5s
              warm_white: 20%
              cold_white: 100%
      - strobe:
          name: "Alternance rapide"
          colors:
            - duration: 3s
              transition_length: 0.5s
              warm_white: 100%
              cold_white: 20%
            - duration: 3s
              transition_length: 0.5s
              warm_white: 20%
              cold_white: 100%
      - strobe:
          name: "Alternance très rapide"
          colors:
            - duration: 0.5s
              transition_length: 0.1s
              warm_white: 100%
              cold_white: 20%
            - duration: 0.5s
              transition_length: 0.1s
              warm_white: 20%
              cold_white: 100%
  - platform: cwww
    name: "Guirlande 2"
    id: guirlande2
    cold_white: channel2_pin1
    warm_white: channel2_pin2
    cold_white_color_temperature: *cold
    warm_white_color_temperature: *warm
    effects: *effects

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      inverted: true  # interrupteur NC
      mode:
        input: true
        pulldown: true  # l'interrupteur apporte le +3.3V en NC
                        # et flottant quand appuyé, donc besoin
                        # d'un pull-down pour amener à 0V
    name: "Interrupteur"
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - if:
            condition:
              light.is_off: button_led
            then:
              - light.turn_on:
                  id: guirlande1
                  effect: *effet_par_defaut_ch1
              - light.turn_on:
                  id: guirlande2
                  effect: *effet_par_defaut_ch2
            else:
              - light.turn_off:
                  id: guirlande1
              - light.turn_off:
                  id: guirlande2
        - light.toggle: button_led

switch:
  - platform: template
    name: "Désynchronisation Bip bip 2"
    id: desync_switch
    icon: mdi:sync-off
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(desync_enabled);
    turn_on_action:
      - globals.set:
          id: desync_enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: desync_enabled
          value: 'false'
