---
# Branchements
# ------------
#
# GPIO27 : prise 1 - rouge et orange
# GPIO26 : prise 1 - vert et bleu
# GPIO25 : prise 2 - rouge et orange
# GPIO33 : prise 2 - vert et bleu
#
# GPIO32 : led sur interrupteur
# GPIO14 : interrupteur

substitutions:
  devicename: guirlande-a-bouboules
  upper_devicename: Guirlande a bouboules

packages:
  device_base: !include common/device_base.yaml
  device_esp32: !include common/device_esp32.yaml

esphome:
  name_add_mac_suffix: false
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: button_led
          brightness: 100%
      - light.turn_on:
          id: guirlande1
          effect: &effet_par_defaut "Aléatoire lent"
      - light.turn_on:
          id: guirlande2
          effect: *effet_par_defaut

esp32:
  board: az-delivery-devkit-v4

logger:
  level: INFO
  #level: DEBUG
  #level: VERBOSE
  #level: VERY_VERBOSE
  #logs:
  #  scheduler: INFO

wifi:
  manual_ip:
    # pour une connection rapide, et pour que le conteneur docker esphome puisse trouver l'ESP sans mDNS
    static_ip: 192.168.1.186
    gateway: 192.168.1.1
    subnet: 255.255.255.0

## Device-specific

preferences:
  flash_write_interval: 10min


interval:
  - interval: 1s
    then:
      - if:
          condition:
            or:
              - light.is_on: guirlande1
              - light.is_on: guirlande2
          then:
            - light.turn_on:
                id: button_led
                brightness: 100%
          else:
            - light.turn_off:
                id: button_led

# inspiration : https://github.com/esphome/feature-requests/issues/2501
output:
  - platform: ledc
    id: channel1_pin1
    inverted: true
    pin:
      number: 27
      inverted: True
    channel: 0
    max_power: 50%
  - platform: ledc
    id: channel1_pin2
    pin: 26
    channel: 2
    max_power: 50%
  - platform: ledc
    id: channel2_pin1
    inverted: true
    pin:
      number: 25
      inverted: True
    channel: 4
    max_power: 50%
  - platform: ledc
    id: channel2_pin2
    pin: 33
    channel: 6
    max_power: 50%
  - platform: ledc
    id: push_button_led
    pin: 32
    channel: 1


light:
  - platform: status_led
    internal: true
    id: status_led_shared
    output: push_button_led
  - platform: monochromatic
    name: "LED sur interrupteur"
    id: button_led
    output: push_button_led
  - platform: cwww
    name: "Guirlande 1"
    id: guirlande1
    cold_white: channel1_pin1
    warm_white: channel1_pin2
    cold_white_color_temperature: &cold 0 Mireds
    warm_white_color_temperature: &warm 500 Mireds
    effects: &effects
      - strobe:
          name: "Arc-en-ciel"
          colors:
            - duration: 10s
              transition_length: 2s
              cold_white: 100%
              warm_white: 100%
            - duration: 1s
              transition_length: 0.2s
              cold_white: 100%
              warm_white: 20%
            - duration: 10s
              transition_length: 2s
              cold_white: 100%
              warm_white: 100%
            - duration: 1s
              transition_length: 0.2s
              cold_white: 20%
              warm_white: 100%
      - flicker:
          name: "Scintillement profond"
          alpha: 50%
          intensity: 50%
      - flicker:
          name: "Scintillement léger"
          alpha: 80%
          intensity: 10%
      - random:
          name: "Aléatoire lent"
          transition_length: 1s
          update_interval: 2s
      - random:
          name: "Aléatoire moyen"
          transition_length: 0.4s
          update_interval: 0.4s
      - random:
          name: "Aléatoire rapide"
          transition_length: 0.1s
          update_interval: 0.1s
      - random:
          name: "Aléatoire énervé"
          transition_length: 0.02s
          update_interval: 0.02s
      - strobe:
          name: "Alternance lente"
          colors:
            - duration: 7s
              transition_length: 5s
              warm_white: 100%
              cold_white: 20%
            - duration: 7s
              transition_length: 5s
              warm_white: 20%
              cold_white: 100%
      - strobe:
          name: "Alternance rapide"
          colors:
            - duration: 3s
              transition_length: 0.5s
              warm_white: 100%
              cold_white: 20%
            - duration: 3s
              transition_length: 0.5s
              warm_white: 20%
              cold_white: 100%
      - strobe:
          name: "Alternance très rapide"
          colors:
            - duration: 0.5s
              transition_length: 0.1s
              warm_white: 100%
              cold_white: 20%
            - duration: 0.5s
              transition_length: 0.1s
              warm_white: 20%
              cold_white: 100%
  - platform: cwww
    name: "Guirlande 2"
    id: guirlande2
    cold_white: channel2_pin1
    warm_white: channel2_pin2
    cold_white_color_temperature: *cold
    warm_white_color_temperature: *warm
    effects: *effects

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      inverted: true  # interrupteur NC
      mode:
        input: true
        pulldown: true  # l'interrupteur apporte le +3.3V en NC
                        # et flottant quand appuyé, donc besoin
                        # d'un pull-down pour amener à 0V
    name: "Interrupteur"
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - if:
            condition:
              light.is_off: button_led
            then:
              - light.turn_on:
                  id: guirlande1
                  effect: *effet_par_defaut
              - light.turn_on:
                  id: guirlande2
                  effect: *effet_par_defaut
            else:
              - light.turn_off:
                  id: guirlande1
              - light.turn_off:
                  id: guirlande2
        - light.toggle: button_led
