---
# Branchements
# ------------
#
# GPIO27 : prise 1 - rouge et orange
# GPIO26 : prise 1 - vert et bleu
# GPIO25 : prise 2 - rouge et orange
# GPIO33 : prise 2 - vert et bleu
#
# GPIO32 : led sur interrupteur
# GPIO14 : interrupteur

substitutions:
  devicename: guirlande-a-bouboules
  upper_devicename: Guirlande a bouboules

packages:
  device_base: !include common/device_base.yaml
  device_esp32: !include common/device_esp32.yaml

esphome:
  name_add_mac_suffix: false

esp32:
  board: az-delivery-devkit-v4

logger:
  level: INFO
  #level: INFO  ## minimum DEBUG obligatoire pour dumper les codes infrarouges recus, VERBOSE pour le multi-click
  #level: DEBUG
  #level: VERBOSE
  #level: VERY_VERBOSE
  #logs:
  #  scheduler: INFO

wifi:
  manual_ip:
    # pour une connection rapide, et pour que le conteneur docker esphome puisse trouver l'ESP sans mDNS
    static_ip: 192.168.1.186
    gateway: 192.168.1.1
    subnet: 255.255.255.0

## Device-specific

preferences:
  flash_write_interval: 10min

# inspiration : https://github.com/esphome/feature-requests/issues/2501
output:
  - platform: ledc
    id: channel1_pin1
    inverted: true
    pin:
      number: 27
      inverted: True
    channel: 0
    max_power: 50%
  - platform: ledc
    id: channel1_pin2
    pin: 26
    channel: 2
    max_power: 50%
  - platform: ledc
    id: channel2_pin1
    inverted: true
    pin:
      number: 25
      inverted: True
    channel: 4
    max_power: 50%
  - platform: ledc
    id: channel2_pin2
    pin: 33
    channel: 6
    max_power: 50%
  - platform: ledc
    id: push_button_led
    pin: 32
    channel: 1


light:
  - platform: cwww
    name: "Guirlande 1"
    cold_white: channel1_pin1
    warm_white: channel1_pin2
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
  - platform: cwww
    name: "Guirlande 2"
    cold_white: channel2_pin1
    warm_white: channel2_pin2
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
  - platform: monochromatic
    name: "LED sur interrupteur"
    output: push_button_led

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      inverted: true  # interrupteur NC
      mode:
        input: true
        pulldown: true  # l'interrupteur apporte le +3.3V en NC
                        # et flottant quand appuyé, donc besoin
                        # d'un pull-down pour amener à 0V
    name: "Interrupteur"
