---
substitutions:
  device_name: chambre_raphael
  friendly_name: Chambre de Raphaël

## Boilerplate

esphome:
  name: ${device_name}
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: Fallback ${device_name}

  manual_ip:
    # pour une connection rapide, et pour que le conteneur docker esphome puisse trouver l'ESP sans mDNS
    static_ip: 192.168.1.26
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# si pas de connexion WiFi, créer un hotspot wifi
#captive_portal:

logger:
  level: INFO

api:

ota:
  password: !secret ota_password


## Device-specific

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: ${friendly_name} Button Light
    effects:
      - random:
      - random:
          name: Random fast
          transition_length: 0.5s
          update_interval: 0.5s
      - flicker:
      - addressable_rainbow:
      - strobe:
      - automation:
          name: Breathe
          sequence:
            - light.turn_on:
                id: status_led
                brightness: 100%
                transition_length: 2s
            - delay: 0.7s
            - light.turn_on:
                id: status_led
                brightness: 20%
                transition_length: 5s
            - delay: 1.5s

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: ${friendly_name} Button
    on_press:
      then:
        - light.toggle: status_led

switch:
  - platform: restart
    name: "${friendly_name} Reboot"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: ${friendly_name} Uptime Sensor

# IR Transmitter
remote_transmitter:
  - pin:
      number: 12
    carrier_duty_percent: 50%
    id: ir_transmitter
