---
esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  #fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename} Hotspot
    password: "Entrap4-Polish-Catcall"


# si pas de connexion WiFi, créer un hotspot wifi
captive_portal:

# Enable logging
logger:
  level: INFO
  #level: INFO  ## minimum DEBUG obligatoire pour dumper les codes infrarouges recus, VERBOSE pour le multi-click
  #level: DEBUG
  #level: VERBOSE
  #level: VERY_VERBOSE

api:

ota:
  - platform: esphome
    password: !secret ota_password

switch:
  - platform: restart
    name: Reboot

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 600s
  - platform: uptime
    name: Uptime Sensor

text_sensor:
  - platform: wifi_info
    # ip_address:
    #   name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address
